### PR TITLE
Fix repository link

### LINKED ISSUE #1: wrong repository link on crates.io
hi. thanks for the list. however on crates.io, if you click on repository, it takes you to another unrelated repository instead of this one. will be nice if you can fix that before someone reports this crate as "malicious" (actually someone already did )

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Fixes #1 

This should fix the issue but it will be reflected only in a new release iirc. 
Also the homepage seems wrong as well but I don't know what to change it to so leaving it to you.

### CODE REVIEW

**Comment by wujunze** [comment]
LGTM

**Comment by wujunze** [comment]
Thanks @Dylan-DPC

**Comment by 0xpr03** [comment]
@wujunze you still have to push a new version on crates.io, this bug is still active

**Comment by wujunze** [comment]
> @wujunze you still have to push a new version on crates.io, this bug is still active

OK Thanks    @0xpr03

**Pull request merged**
